package org.pojos;

// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cluster generated by hbm2java
 */
public class Cluster implements java.io.Serializable {

	private Integer clusterid;
	private int nofpools;
	private String clustername;
	private Set pools = new HashSet(0);

	public Cluster() {
	}

	public Cluster(int nofpools, String clustername) {
		this.nofpools = nofpools;
		this.clustername = clustername;
	}

	public Cluster(int nofpools, String clustername, Set pools) {
		this.nofpools = nofpools;
		this.clustername = clustername;
		this.pools = pools;
	}

	public Integer getClusterid() {
		return this.clusterid;
	}

	public void setClusterid(Integer clusterid) {
		this.clusterid = clusterid;
	}

	public int getNofpools() {
		return this.nofpools;
	}

	public void setNofpools(int nofpools) {
		this.nofpools = nofpools;
	}

	public String getClustername() {
		return this.clustername;
	}

	public void setClustername(String clustername) {
		this.clustername = clustername;
	}

	public Set getPools() {
		return this.pools;
	}

	public void setPools(Set pools) {
		this.pools = pools;
	}

}
