package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pooltype generated by hbm2java
 */
public class Pooltype implements java.io.Serializable {

	private Integer pooltypeid;
	private String pooltypestringvalue;
	private Set pools = new HashSet(0);

	public Pooltype() {
	}

	public Pooltype(String pooltypestringvalue) {
		this.pooltypestringvalue = pooltypestringvalue;
	}

	public Pooltype(String pooltypestringvalue, Set pools) {
		this.pooltypestringvalue = pooltypestringvalue;
		this.pools = pools;
	}

	public Integer getPooltypeid() {
		return this.pooltypeid;
	}

	public void setPooltypeid(Integer pooltypeid) {
		this.pooltypeid = pooltypeid;
	}

	public String getPooltypestringvalue() {
		return this.pooltypestringvalue;
	}

	public void setPooltypestringvalue(String pooltypestringvalue) {
		this.pooltypestringvalue = pooltypestringvalue;
	}

	public Set getPools() {
		return this.pools;
	}

	public void setPools(Set pools) {
		this.pools = pools;
	}

}
