package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Reviewratings generated by hbm2java
 */
public class Reviewratings implements java.io.Serializable {

	private Integer reviewratingsid;
	private String reviewratingsstringvalue;
	private Set reviews = new HashSet(0);

	public Reviewratings() {
	}

	public Reviewratings(String reviewratingsstringvalue) {
		this.reviewratingsstringvalue = reviewratingsstringvalue;
	}

	public Reviewratings(String reviewratingsstringvalue, Set reviews) {
		this.reviewratingsstringvalue = reviewratingsstringvalue;
		this.reviews = reviews;
	}

	public Integer getReviewratingsid() {
		return this.reviewratingsid;
	}

	public void setReviewratingsid(Integer reviewratingsid) {
		this.reviewratingsid = reviewratingsid;
	}

	public String getReviewratingsstringvalue() {
		return this.reviewratingsstringvalue;
	}

	public void setReviewratingsstringvalue(String reviewratingsstringvalue) {
		this.reviewratingsstringvalue = reviewratingsstringvalue;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

}
