package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Review generated by hbm2java
 */
public class Review implements java.io.Serializable {

	private Integer reviewid;
	private User user;
	private Reviewratings reviewratings;
	private String reviewcomment;
	private Date reviewtimestamp;

	public Review() {
	}

	public Review(User user, Reviewratings reviewratings, Date reviewtimestamp) {
		this.user = user;
		this.reviewratings = reviewratings;
		this.reviewtimestamp = reviewtimestamp;
	}

	public Review(User user, Reviewratings reviewratings, String reviewcomment,
			Date reviewtimestamp) {
		this.user = user;
		this.reviewratings = reviewratings;
		this.reviewcomment = reviewcomment;
		this.reviewtimestamp = reviewtimestamp;
	}

	public Integer getReviewid() {
		return this.reviewid;
	}

	public void setReviewid(Integer reviewid) {
		this.reviewid = reviewid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Reviewratings getReviewratings() {
		return this.reviewratings;
	}

	public void setReviewratings(Reviewratings reviewratings) {
		this.reviewratings = reviewratings;
	}

	public String getReviewcomment() {
		return this.reviewcomment;
	}

	public void setReviewcomment(String reviewcomment) {
		this.reviewcomment = reviewcomment;
	}

	public Date getReviewtimestamp() {
		return this.reviewtimestamp;
	}

	public void setReviewtimestamp(Date reviewtimestamp) {
		this.reviewtimestamp = reviewtimestamp;
	}

}
