package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Triptype generated by hbm2java
 */
public class Triptype implements java.io.Serializable {

	private Integer triptypeid;
	private String triptypestringvalue;
	private Set trips = new HashSet(0);

	public Triptype() {
	}

	public Triptype(String triptypestringvalue) {
		this.triptypestringvalue = triptypestringvalue;
	}

	public Triptype(String triptypestringvalue, Set trips) {
		this.triptypestringvalue = triptypestringvalue;
		this.trips = trips;
	}

	public Integer getTriptypeid() {
		return this.triptypeid;
	}

	public void setTriptypeid(Integer triptypeid) {
		this.triptypeid = triptypeid;
	}

	public String getTriptypestringvalue() {
		return this.triptypestringvalue;
	}

	public void setTriptypestringvalue(String triptypestringvalue) {
		this.triptypestringvalue = triptypestringvalue;
	}

	public Set getTrips() {
		return this.trips;
	}

	public void setTrips(Set trips) {
		this.trips = trips;
	}

}
