package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Trip generated by hbm2java
 */
public class Trip implements java.io.Serializable {

	private Integer tripid;
	private User user;
	private Triptype triptype;
	private Pool pool;
	private Vehicle vehicle;
	private Tripstatus tripstatus;
	private int tripattendance;
	private Date tripstarttime;
	private Date tripendtime;

	public Trip() {
	}

	public Trip(User user, Triptype triptype, Pool pool, Vehicle vehicle,
			int tripattendance, Date tripstarttime, Date tripendtime) {
		this.user = user;
		this.triptype = triptype;
		this.pool = pool;
		this.vehicle = vehicle;
		this.tripattendance = tripattendance;
		this.tripstarttime = tripstarttime;
		this.tripendtime = tripendtime;
	}

	public Trip(User user, Triptype triptype, Pool pool, Vehicle vehicle,
			Tripstatus tripstatus, int tripattendance, Date tripstarttime,
			Date tripendtime) {
		this.user = user;
		this.triptype = triptype;
		this.pool = pool;
		this.vehicle = vehicle;
		this.tripstatus = tripstatus;
		this.tripattendance = tripattendance;
		this.tripstarttime = tripstarttime;
		this.tripendtime = tripendtime;
	}

	public Integer getTripid() {
		return this.tripid;
	}

	public void setTripid(Integer tripid) {
		this.tripid = tripid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Triptype getTriptype() {
		return this.triptype;
	}

	public void setTriptype(Triptype triptype) {
		this.triptype = triptype;
	}

	public Pool getPool() {
		return this.pool;
	}

	public void setPool(Pool pool) {
		this.pool = pool;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public Tripstatus getTripstatus() {
		return this.tripstatus;
	}

	public void setTripstatus(Tripstatus tripstatus) {
		this.tripstatus = tripstatus;
	}

	public int getTripattendance() {
		return this.tripattendance;
	}

	public void setTripattendance(int tripattendance) {
		this.tripattendance = tripattendance;
	}

	public Date getTripstarttime() {
		return this.tripstarttime;
	}

	public void setTripstarttime(Date tripstarttime) {
		this.tripstarttime = tripstarttime;
	}

	public Date getTripendtime() {
		return this.tripendtime;
	}

	public void setTripendtime(Date tripendtime) {
		this.tripendtime = tripendtime;
	}

}
