package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usertypes generated by hbm2java
 */
public class Usertypes implements java.io.Serializable {

	private Integer usertypeid;
	private String usertypestringvalue;
	private Set users = new HashSet(0);

	public Usertypes() {
	}

	public Usertypes(String usertypestringvalue) {
		this.usertypestringvalue = usertypestringvalue;
	}

	public Usertypes(String usertypestringvalue, Set users) {
		this.usertypestringvalue = usertypestringvalue;
		this.users = users;
	}

	public Integer getUsertypeid() {
		return this.usertypeid;
	}

	public void setUsertypeid(Integer usertypeid) {
		this.usertypeid = usertypeid;
	}

	public String getUsertypestringvalue() {
		return this.usertypestringvalue;
	}

	public void setUsertypestringvalue(String usertypestringvalue) {
		this.usertypestringvalue = usertypestringvalue;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
