package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userid;
	private Usertypes usertypes;
	private int phonenumber;
	private String boardingpt;
	private String emailid;
	private String name;
	private String org;
	private String password;
	private String gender;
	private String address1;
	private String address2;
	private String address3;
	private byte[] candrive;
	private String licenseno;
	private Set trips = new HashSet(0);
	private Set reviews = new HashSet(0);
	private Set vehicles = new HashSet(0);
	private Set pools = new HashSet(0);

	public User() {
	}

	public User(String userid, Usertypes usertypes, int phonenumber,
			String boardingpt, String emailid, String name, String org,
			String password) {
		this.userid = userid;
		this.usertypes = usertypes;
		this.phonenumber = phonenumber;
		this.boardingpt = boardingpt;
		this.emailid = emailid;
		this.name = name;
		this.org = org;
		this.password = password;
	}

	public User(String userid, Usertypes usertypes, int phonenumber,
			String boardingpt, String emailid, String name, String org,
			String password, String gender, String address1, String address2,
			String address3, byte[] candrive, String licenseno, Set trips,
			Set reviews, Set vehicles, Set pools) {
		this.userid = userid;
		this.usertypes = usertypes;
		this.phonenumber = phonenumber;
		this.boardingpt = boardingpt;
		this.emailid = emailid;
		this.name = name;
		this.org = org;
		this.password = password;
		this.gender = gender;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.candrive = candrive;
		this.licenseno = licenseno;
		this.trips = trips;
		this.reviews = reviews;
		this.vehicles = vehicles;
		this.pools = pools;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public Usertypes getUsertypes() {
		return this.usertypes;
	}

	public void setUsertypes(Usertypes usertypes) {
		this.usertypes = usertypes;
	}

	public int getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(int phonenumber) {
		this.phonenumber = phonenumber;
	}

	public String getBoardingpt() {
		return this.boardingpt;
	}

	public void setBoardingpt(String boardingpt) {
		this.boardingpt = boardingpt;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrg() {
		return this.org;
	}

	public void setOrg(String org) {
		this.org = org;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	public byte[] getCandrive() {
		return this.candrive;
	}

	public void setCandrive(byte[] candrive) {
		this.candrive = candrive;
	}

	public String getLicenseno() {
		return this.licenseno;
	}

	public void setLicenseno(String licenseno) {
		this.licenseno = licenseno;
	}

	public Set getTrips() {
		return this.trips;
	}

	public void setTrips(Set trips) {
		this.trips = trips;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set vehicles) {
		this.vehicles = vehicles;
	}

	public Set getPools() {
		return this.pools;
	}

	public void setPools(Set pools) {
		this.pools = pools;
	}

}
