package org.pojos;
// default package
// Generated Nov 1, 2015 12:44:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private String vehiclenumber;
	private User user;
	private Integer capacity;
	private Set trips = new HashSet(0);

	public Vehicle() {
	}

	public Vehicle(String vehiclenumber, User user) {
		this.vehiclenumber = vehiclenumber;
		this.user = user;
	}

	public Vehicle(String vehiclenumber, User user, Integer capacity, Set trips) {
		this.vehiclenumber = vehiclenumber;
		this.user = user;
		this.capacity = capacity;
		this.trips = trips;
	}

	public String getVehiclenumber() {
		return this.vehiclenumber;
	}

	public void setVehiclenumber(String vehiclenumber) {
		this.vehiclenumber = vehiclenumber;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public Set getTrips() {
		return this.trips;
	}

	public void setTrips(Set trips) {
		this.trips = trips;
	}

}
